name: Docker Build and Publish (Lite)

on:
  push:
    tags: [ "v*" ]
  pull_request:
    types: [closed]
    branches: [ "develop", "rel/*" ]
  workflow_dispatch:

jobs:
  build-and-publish-lite:
    uses: ./.github/workflows/docker-build-publish-reusable.yml
    with:
      image-suffix: '-lite'
      dockerfile: 'Dockerfile-lite'
    secrets: inherit
